# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 's02e04_mvc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for s02e04_mvc
  pod 'Alamofire', '~> 5.2'
  pod 'RealmSwift'
end
