# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 's02e03_Reactive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for s02e03_Reactive
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
end
