# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 's02e09-socials' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for s02e09-socials
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'SnapKit', '~> 5.0.0'
  pod 'VK-ios-sdk'
  pod 'GoogleSignIn'
end
